apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sample
        image: demoimage
        ports:
        - containerPort: 6379
          name: demoimage
---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  ports:
  - port: 6379
  selector:
    app: sample
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sample
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sample
        image: hemosoftdemom.azurecr.io/demoimage:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: demoimage
          value: "sample"
---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sample