apiVersion: v1
kind: Service
metadata:
  name: my-demoimage-svc
  labels:
    app: demoimage
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demoimage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoimage-deployment
  labels:
    app: demoimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoimage
  template:
    metadata:
      labels:
        app: demoimage
    spec:
      containers:
      - name: demoimage
        image: hemosoftdemom.azurecr.io/demoimage:v1
        ports:
        - containerPort: 80