apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: neslihansampleproject 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neslihansampleproject 
    spec:
      containers:
        - name: neslihansampleproject 
          image: hemosoft.azurecr.io/neslihansampleproject
          ports:
          - containerPort: 80